pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t cloud9-backend ./backend'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8000:8000 cloud9-backend'
            }
        }
    }
}
